
delimiter $$
CREATE PROCEDURE myFunction()
Begin
	declare i int default 1;
    while (i<365) DO
		insert into user_query(NUM_PLAYGROUNDS,NUM_PUBLIC_SCHOOLS,NUM_CATHOLIC_SCHOOLS,NUM_SINGLE,NUM_DUPLEX,NUM_ROW_HOUSE,NUM_APARTMENT_FIVE,NUM_APARTMENT_FOUR,NUM_HOTEL,NUM_AGE_FOURTEEN,NUM_AGE_THIRTYFIVE,NUM_AGE_SIXTY,NUM_AGE_SIXTYPLUS,NUM_EMPLOYMENT_STUDENT,NUM_EMPLOYMENT_UNEMPLOYED,NUM_EMPLOYMENT_EMPLOYED) values (FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0,FLOOR(RAND() * 100) + 0);
		set i = i+1;
    END while;
END$$

delimiter ;
call myFunction();
