DROP DATABASE IF EXISTS mm811project; 
CREATE DATABASE mm811project;
USE mm811project;
CREATE TABLE IF NOT EXISTS app_metadata (
  APP_NAME varchar(30) NOT NULL,
  VERSION float(5,2) NOT NULL,
  CREATE_TS timestamp NOT NULL 
      DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TS timestamp NULL
      ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS users (
  ID int(9) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LAST_NAME varchar(30) NOT NULL,
  FIRST_NAME varchar(30) NOT NULL,
  USER_NAME varchar(30) unique NOT NULL,
  USER_PWD varchar(30) NOT NULL,
  CREATE_TS timestamp NOT NULL 
      DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TS timestamp NULL
      ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS relative_dataset (
  ID int(9) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DATASET_NAME varchar(30) NOT NULL,
  DATASET_URL varchar(300) NOT NULL,
  DATASET_ID int(20) NOT NULL,
  DATASET_LASTUPADE timestamp NOT NULL,
  DATASET_MAX_VALUE int(9) unsigned NOT NULL,
  CREATE_TS timestamp NOT NULL 
      DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TS timestamp NULL
      ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS major_dataset (
  ID int(9) unsigned NOT NULL PRIMARY KEY,
  NEIGHBOURHOOD_NAME varchar(30) NOT NULL,
  NUM_PLAYGROUNDS int(9) unsigned NOT NULL,
  NUM_PUBLIC_SCHOOLS int(9) unsigned NOT NULL,
  NUM_CATHOLIC_SCHOOLS int(9) unsigned NOT NULL,
  NUM_SINGLE int(9) unsigned NOT NULL,
  NUM_DUPLEX int(9) unsigned NOT NULL,
  NUM_ROW_HOUSE int(9) unsigned NOT NULL,
  NUM_APARTMENT_FIVE int(9) unsigned NOT NULL,
  NUM_APARTMENT_FOUR int(9) unsigned NOT NULL,
  NUM_HOTEL int(9) unsigned NOT NULL,
  NUM_AGE_FOURTEEN   int(9) unsigned NOT NULL,
  NUM_AGE_THIRTYFIVE   int(9) unsigned NOT NULL,
  NUM_AGE_SIXTY  int(9) unsigned NOT NULL,
  NUM_AGE_SIXTYPLUS   int(9) unsigned NOT NULL,
  NUM_EMPLOYMENT_STUDENT   int(9) unsigned NOT NULL,
  NUM_EMPLOYMENT_UNEMPLOYED   int(9) unsigned NOT NULL,
  NUM_EMPLOYMENT_EMPLOYED   int(9) unsigned NOT NULL,
  CREATE_TS timestamp NOT NULL 
      DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TS timestamp NULL
      ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS user_query (
  ID int(9) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NUM_PLAYGROUNDS bool  NOT NULL,
  NUM_PUBLIC_SCHOOLS bool  NOT NULL,
  NUM_CATHOLIC_SCHOOLS bool  NOT NULL,
  NUM_SINGLE bool NOT NULL,
  NUM_DUPLEX bool NOT NULL,
  NUM_ROW_HOUSE bool NOT NULL,
  NUM_APARTMENT_FIVE bool NOT NULL,
  NUM_APARTMENT_FOUR bool NOT NULL,
  NUM_HOTEL bool NOT NULL,
  NUM_AGE   int(9) unsigned NOT NULL,
  NUM_EMPLOYMENT   int(9) unsigned NOT NULL,
  CREATE_TS timestamp NOT NULL 
      DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS neighbourhood_tmp (
  NEIGHBOURHOOD_NAME varchar(80)  NOT NULL PRIMARY KEY,
  NEIGHBOURHOOD_AREA varchar(100000),
  NEIGHBOURHOOD_LATI float(30)  ,
  NEIGHBOURHOOD_LONG float(30) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

INSERT INTO app_metadata
(APP_NAME, VERSION) 
VALUES 
("MM801 Project", 1.00);

INSERT INTO users
(LAST_NAME,FIRST_NAME,USER_NAME,USER_PWD)
VALUES 
("Sun","Alvin","admin1","admin");
INSERT INTO users
(LAST_NAME,FIRST_NAME,USER_NAME,USER_PWD)
VALUES 
("Li","Hongzu","admin2","admin");

INSERT INTO relative_dataset
(DATASET_NAME,DATASET_URL,DATASET_ID,DATASET_LASTUPADE,DATASET_MAX_VALUE)
VALUES 
("","","","","");

INSERT INTO `major_dataset` (`ID`, `NEIGHBOURHOOD_NAME`, `NUM_PLAYGROUNDS`, `NUM_PUBLIC_SCHOOLS`, `NUM_CATHOLIC_SCHOOLS`, `NUM_SINGLE`, `NUM_DUPLEX`, `NUM_ROW_HOUSE`, `NUM_APARTMENT_FIVE`, `NUM_APARTMENT_FOUR`, `NUM_HOTEL`, `NUM_AGE_FOURTEEN`, `NUM_AGE_THIRTYFIVE`, `NUM_AGE_SIXTY`, `NUM_AGE_SIXTYPLUS`, `NUM_EMPLOYMENT_STUDENT`, `NUM_EMPLOYMENT_UNEMPLOYED`, `NUM_EMPLOYMENT_EMPLOYED`, `CREATE_TS`, `UPDATE_TS`) VALUES ('1', 'Abbottsfield', '20', '2', '3', '100', '100', '100', '200', '200', '2', '10000', '20000', '15000', '5000', '20000', '20000', '5000', CURRENT_TIMESTAMP, NULL);

INSERT INTO `major_dataset` (`ID`, `NEIGHBOURHOOD_NAME`, `NUM_PLAYGROUNDS`, `NUM_PUBLIC_SCHOOLS`, `NUM_CATHOLIC_SCHOOLS`, `NUM_SINGLE`, `NUM_DUPLEX`, `NUM_ROW_HOUSE`, `NUM_APARTMENT_FIVE`, `NUM_APARTMENT_FOUR`, `NUM_HOTEL`, `NUM_AGE_FOURTEEN`, `NUM_AGE_THIRTYFIVE`, `NUM_AGE_SIXTY`, `NUM_AGE_SIXTYPLUS`, `NUM_EMPLOYMENT_STUDENT`, `NUM_EMPLOYMENT_UNEMPLOYED`, `NUM_EMPLOYMENT_EMPLOYED`, `CREATE_TS`, `UPDATE_TS`) VALUES ('2', 'Anthony Henday', '10', '1', '4', '120', '120', '80', '100', '150', '3', '20000', '10000', '25000', '6000', '10000', '30000', '2000', CURRENT_TIMESTAMP, NULL);